# Generated from anatomietermen_latijn_ingevuld.xlsx.
# Keys are normalized English answer terms; values are user-supplied Latin terms.

FILLED_LATIN_TERMS = {'4th metatarsal': 'metatarsium IV',
 '5th metatarsal base': 'metatarsium V',
 'air in the left eustachian tube': 'tuba auditiva or (tuba Eustachii) sinistra',
 'air in the right eustachian tube': 'tuba auditiva or (tuba Eustachii) dextra',
 'annulusfibrosus': 'annulus fibrosus',
 'antarcc1': 'arcus anterior C1',
 'anterior horn of left lateral ventricle': 'cornu anterius ventriculi lateralis sinistri',
 'anterior horn of right lateral ventricle': 'cornu anterius ventriculi lateralis dextra',
 'anterior interhemispheric fissure': 'pars anterior fissurae longitudinalis cerebri',
 'anterior lobe of pituitary': 'lobus anterior hypophysis (adenohypophysis)',
 'anterior lobe of pituitary gland': 'lobus anterior glandulae pituitariae (hypophysis)',
 'anterior myometrium': 'myometrium anterius',
 'anterior myometrium of uterus': 'myometrium anterius uteri',
 'anterior wall of urinary bladder': 'paries anterior vesicae urinariae',
 'anterior wall of uterine myometrium': 'paries anterior myometrii uteri',
 'apophysis of trochanter major': 'apophysis trochanteris majoris',
 'articular eminence of temporal bone': 'eminentia articularis ossis temporalis',
 'atlanto axial joint': 'articulatio atlantoaxialis',
 'axillary tail of breast': 'processus axillaris mammae (cauda axillaris)',
 "baker's cyst": 'cystis poplitea (Baker)',
 'basal vein of rosenthal': 'vena basalis (Rosenthal)',
 'base of 1mc': 'basis ossis metacarpi I',
 'base of metatarsal': 'basis ossis metatarsi',
 'base of prostate gland': 'basis prostatae',
 'baseof1mc': 'basis ossis metacarpi I',
 'baseof2': 'basis ossis metacarpi II',
 'baseof2nd': 'basis ossis metacarpi II',
 'biceps femoris tendon': 'tendo musculi bicipitis femoris',
 'bicepsshorthead': 'caput breve musculi bicipitis brachii',
 'body of pubis': 'corpus ossis pubis',
 'bodypubis': 'corpus ossis pubis',
 'breast adipose tissu': 'textus adiposus mammae',
 'breast adipose tissue': 'textus adiposus mammae',
 'breast parenchyma': 'parenchyma mammae',
 'breast skin': 'cutis mammae',
 'breast skin line': 'linea cutis mammae',
 'bulbar portion of urethra': 'pars bulbaris urethrae (pars spongiosa)',
 'bulbar urethra': 'urethra bulbaris (pars spongiosa urethrae)',
 'calcaneus2': 'calcaneus',
 'cap': 'os capitatum',
 'capepiphysis': 'epiphysis capitis femoris',
 'capitate2': 'os capitatum',
 'capitellum2': 'capitulum humeri',
 'capitellum3': 'capitulum humeri',
 'capitellumepi': 'epiphysis capituli humeri',
 'cavernous segment of internal carotid artery': 'pars cavernosa arteriae carotidis internae',
 'cavernous segment of right internal carotid artery': 'pars cavernosa arteriae carotidis internae dextrae',
 'central gland of prostate': 'zona centralis prostatae (glandula centralis)',
 'cerebellomedullaris cistern': 'cisterna cerebellomedullaris',
 'cerebellomedullary cistern': 'cisterna cerebellomedullaris',
 'cervical oesophagus': 'pars cervicalis oesophagi',
 'chopart joint': 'articulatio tarsi transversa (Chopart)',
 'circumflex femoral artery': 'arteria circumflexa femoris',
 'cistern of the great cerebral vein': 'cisterna venae magnae cerebri (cisterna quadrigeminalis)',
 'condylar process of mandible': 'processus condylaris mandibulae',
 'condyloid process of mandible': 'processus condylaris mandibulae',
 'contrast in endometrial cavity': 'cavitas uteri (cavitas endometrialis)',
 'contrast in urinary bladder': 'vesica urinaria',
 'conusmedullaris': 'conus medullaris',
 'coracoid': 'processus coracoideus',
 'coracoid process center': 'centrum processus coracoidei',
 'coracoid2': 'processus coracoideus',
 'coracoid3': 'processus coracoideus',
 'coracoid4': 'processus coracoideus',
 'coronoid process of left mandible': 'processus coronoideus mandibulae sinistrae',
 'coronoidmandible': 'processus coronoideus mandibulae',
 'corpus c6': 'corpus vertebrae C6',
 'corpus cavernosum': 'corpus cavernosum penis',
 'cortical vein': 'vena corticalis',
 'crus of left corpus cavernosum': 'crus corporis cavernosi sinistri',
 'crus of right corpus cavernosum': 'crus corporis cavernosi dextri',
 'ctmusculoskeletal30': '— (bestandsnaam, geen anatomische term)',
 'cuboid2': 'os cuboideum',
 'dentine': 'dentinum',
 'distal femur': 'extremitas distalis femoris (femur distale)',
 'distal radius': 'extremitas distalis radii (radius distalis)',
 'distal ulna': 'extremitas distalis ulnae (ulna distalis)',
 'distaltibiaepi': 'epiphysis distalis tibiae',
 'distcl': 'extremitas acromialis claviculae (clavicula distalis)',
 'dural venous sinus': 'sinus durae matris',
 'enamel': 'enamelum',
 'endometrial cavity': 'cavitas uteri (cavitas endometrialis)',
 'epiph1stmetaca': 'epiphysis ossis metacarpi I',
 'exiting nerve root': 'radix nervi spinalis exiens',
 'exitingnerve': 'radix nervi spinalis exiens',
 'extensorcarpiradialislongus': 'musculus extensor carpi radialis longus',
 'extensorcarpiulnaris': 'musculus extensor carpi ulnaris',
 'extensordigtendon': 'tendo musculi extensoris digitorum',
 'extensorhallucislongus': 'musculus extensor hallucis longus',
 'extensorindicistendon': 'tendo musculi extensoris indicis',
 'external os of cervix': 'ostium uteri externum (ostium externum cervicis)',
 'extrahepatic inferior vena cava': 'pars extrahepatica venae cavae inferioris',
 'facetjoint': 'articulatio zygapophysialis',
 'facetjoint2': 'articulatio zygapophysialis',
 'femoral condyle': 'condylus femoris',
 'femveinleft': 'vena femoralis sinistra',
 'fibroglandular tissue of breast': 'textus fibroglandularis mammae',
 'firstrib': 'costa prima (costa I)',
 'flexor hallucis longus tendon': 'tendo musculi flexoris hallucis longi',
 'flexordigitorumlongus': 'musculus flexor digitorum longus',
 'flexorpollicuslongus': 'musculus flexor pollicis longus',
 'fluid in the uterine cavity': 'cavitas uteri',
 'fluid in urinary bladder': 'vesica urinaria',
 'foramen obt': 'foramen obturatum',
 'free intraperitoneal spillage of contrast': 'cavitas peritonealis (spatium intraperitoneale)',
 'frontalprocessofzygomaticbone': 'processus frontalis ossis zygomatici',
 'gemellus superior': 'musculus gemellus superior',
 'geniculate arteries': 'arteriae geniculares (genus)',
 'genu of corpus callosum': 'genu corporis callosi',
 "gerota's fascia": 'fascia renalis anterior (Gerota)',
 'glenohu': 'articulatio glenohumeralis',
 'globe': 'bulbus oculi',
 'gluteusmaximus': 'musculus gluteus maximus',
 'gracilis': 'musculus gracilis',
 'gracilis2': 'musculus gracilis',
 'great cerebral vein of galen': 'vena magna cerebri (Galeni)',
 'great trochanter': 'trochanter major',
 'greater horn of hyoid': 'cornu majus ossis hyoidei',
 'greater tuberosity': 'tuberculum majus humeri',
 'head of epididymis': 'caput epididymidis',
 'headgastro': 'caput musculi gastrocnemii',
 'hoffa pat pad': 'corpus adiposum infrapatellare (Hoffa)',
 "hoffa's fat pad": 'corpus adiposum infrapatellare (Hoffa)',
 'hook of hamate': 'hamulus ossis hamati',
 'hookhamate': 'hamulus ossis hamati',
 'hookofhamate': 'hamulus ossis hamati',
 'hookofhm': 'hamulus ossis hamati',
 'horseshoe kidney': 'ren arcuatus (ren equinus)',
 'horseshoe kidney isthmus': 'isthmus renis arcuati',
 'humeral head': 'caput humeri',
 'hypopharynx': 'pars laryngea pharyngis (hypopharynx)',
 'iliac external artery': 'arteria iliaca externa',
 'iliopectinealline': 'linea iliopectinea',
 'iliopsoasmuscle': 'musculus iliopsoas',
 'iliotibial band': 'tractus iliotibialis',
 'iliotibialband': 'tractus iliotibialis',
 'infarticularprocess': 'processus articularis inferior',
 'infborderscap': 'angulus inferior scapulae',
 'inferior articular process': 'processus articularis inferior',
 'inferior border scapula': 'angulus inferior scapulae (margo lateralis)',
 'infraorbitalforamen': 'foramen infraorbitale',
 'infundibulum': 'infundibulum',
 'infundibulum of pituitary gland': 'infundibulum hypophysis',
 'intercondyl': 'fossa intercondylaris',
 'intercondylar notch': 'fossa intercondylaris',
 'intercondyle': 'fossa intercondylaris',
 'interhemispheric fissure': 'fissura longitudinalis cerebri',
 'interlobar vein of kidney': 'vena interlobaris renis',
 'intermediate cuneiform': 'os cuneiforme intermedium',
 'intermediatecuneiform': 'os cuneiforme intermedium',
 'internal cerebral vein': 'vena cerebri interna',
 'intertuberculargroove': 'sulcus intertubercularis',
 'isthmus of thyroid': 'isthmus glandulae thyroideae',
 'isthmus of thyroid gland': 'isthmus glandulae thyroideae',
 'junctional zone of uterus': 'zona juncturalis uteri (myometrium internum)',
 'kidney cortex': 'cortex renalis',
 'labrum': 'labrum glenoidale',
 'lamina': 'lamina arcus vertebrae',
 'laminal3': 'lamina arcus vertebrae L3',
 'latepi': 'epicondylus lateralis',
 'latepicondyl': 'epicondylus lateralis',
 'lateral border of scapula': 'margo lateralis scapulae',
 'lateral cuneiform': 'os cuneiforme laterale',
 'lateral epicondyle': 'epicondylus lateralis',
 'lateral malleolus': 'malleolus lateralis',
 'lateral mass of c1': 'massa lateralis atlantis (C1)',
 'lateral pterygoid': 'musculus pterygoideus lateralis',
 'latmal': 'malleolus lateralis',
 'left alveolar process of maxillary bone': 'processus alveolaris maxillae sinistrae',
 'left ampulla of fallopian tube': 'ampulla tubae uterinae sinistrae',
 'left ampullary portion of fallopian tube': 'pars ampullaris tubae uterinae sinistrae',
 'left basilar part of the occipital bone': 'pars basilaris ossis occipitalis sinistra',
 'left breast main mammary duct': 'ductus lactifer principalis mammae sinistrae',
 'left distal ureter': 'pars distalis ureteris sinistri',
 'left fimbria of fallopian tube': 'fimbriae tubae uterinae sinistrae',
 'left head of caudate nucleus': 'caput nuclei caudati sinistri',
 'left head of epididymis': 'caput epididymidis sinistri',
 'left hemidiaphragm': 'hemidiaphragma sinistrum (pars sinistra diaphragmatis)',
 'left internal cerebral vein': 'vena cerebri interna sinistra',
 'left internal iliac vessels': 'vasa iliaca interna sinistra',
 'left interstitial portion of fallopian tube': 'pars uterina (intramuralis) tubae uterinae sinistrae',
 'left isthmus of fallopian tube': 'isthmus tubae uterinae sinistrae',
 'left lateral pterygoid plate of sphenoid': 'lamina lateralis processus pterygoidei ossis sphenoidalis sinistra',
 'left lobe of thyroid gland': 'lobus sinister glandulae thyroideae',
 'left mastoid air cells': 'cellulae mastoideae sinistrae',
 'left middle nasal turbinate': 'concha nasalis media sinistra',
 'left posterior ethmoidal air cell': 'cellulae ethmoidales posteriores sinistrae',
 'left posterior perirenal fascia': 'fascia renalis posterior sinistra',
 'left proximal ureter': 'pars proximalis ureteris sinistri',
 'left semispinalis capitis muscle': 'musculus semispinalis capitis sinister',
 'left strap muscle': 'musculi infrahyoidei sinistri (strap muscles)',
 'left suprarenal gland': 'glandula suprarenalis sinistra',
 'left transverse sinus': 'sinus transversus sinister',
 'left ureterovesical junction': 'junctio ureterovesicalis sinistra (ostium ureteris sinistri)',
 'leftcommonfem': 'vena femoralis communis sinistra',
 'leftdeepfemart': 'arteria profunda femoris sinistra',
 'lesser tuberosity': 'tuberculum minus humeri',
 'lisfranc joint': 'articulationes tarsometatarsales (Lisfranc)',
 'lister': 'tuberculum dorsale radii (tuberculum Listeri)',
 'login bg': '— (interface-element, geen anatomische term)',
 'long head of biceps': 'caput longum musculi bicipitis brachii',
 'long head of triceps': 'caput longum musculi tricipitis brachii',
 'longheadofbiceps': 'caput longum musculi bicipitis brachii',
 'lower pole of kidney': 'extremitas inferior renis (polus inferior)',
 'lumbarverte': 'vertebra lumbalis',
 'main mammary duct': 'ductus lactifer principalis',
 'major calyx of kidney': 'calyx renalis major',
 'mammillary body of the hypothalamus': 'corpus mammillare',
 'manubriumsternum': 'manubrium sterni',
 'massa intermedia': 'adhesio interthalamica (massa intermedia)',
 'massa intermedia of thalamus': 'adhesio interthalamica (massa intermedia thalami)',
 'mastoid air cells': 'cellulae mastoideae',
 'medial cuneiform': 'os cuneiforme mediale',
 'medial epicondyle': 'epicondylus medialis',
 'medialcondyle': 'condylus medialis',
 'medialcondyle2': 'condylus medialis',
 'medialcondyle3': 'condylus medialis',
 'medialepicondyle': 'epicondylus medialis',
 'medullary pyramid': 'pyramis renalis',
 'medullary pyramid of lower pole of right kidney': 'pyramis renalis poli inferioris renis dextri',
 'medullary pyramid of right kidney': 'pyramis renalis renis dextri',
 'membranous portion of urethra': 'pars membranacea urethrae (pars intermedia)',
 'metacarpophlagneal joint': 'articulatio metacarpophalangea',
 'metaphystibia': 'metaphysis tibiae',
 'middlethirdclavicle': 'corpus claviculae (tertia media)',
 'minor calyx of kidney': 'calyx renalis minor',
 'minor calyx of right kidney': 'calyx renalis minor renis dextri',
 'mra circle of willis': 'circulus arteriosus cerebri (Willisi)',
 'mrimusculoskeletal51': '— (bestandsnaam, geen anatomische term)',
 'mylohyoid': 'musculus mylohyoideus',
 'myometrium of uterus': 'myometrium uteri',
 'neural foramen': 'foramen intervertebrale',
 'obtext3': 'musculus obturatorius externus',
 'obturator externus': 'musculus obturatorius externus',
 'obturator internus': 'musculus obturatorius internus',
 'obturatorinternus': 'musculus obturatorius internus',
 'olecranon process': 'olecranon',
 'omentum': 'omentum',
 'orbital plate': 'lamina orbitalis',
 'ovarian stroma': 'stroma ovarii',
 'parietal layer of tunica vaginalis': 'lamina parietalis tunicae vaginalis testis',
 'pectmaj': 'musculus pectoralis major',
 'pectmajor': 'musculus pectoralis major',
 'pedicle': 'pediculus arcus vertebrae',
 'pediclel5': 'pediculus arcus vertebrae L5',
 'pelvis of left kidney': 'pelvis renalis sinistra',
 'penile portion of urethra': 'pars spongiosa urethrae (pars pendulans)',
 'penile urethra': 'urethra penilis (pars spongiosa urethrae)',
 'peripheral zone of prostate': 'zona peripherica prostatae',
 'perirenal fat': 'capsula adiposa renis (corpus adiposum pararenale)',
 'peroneus longus': 'musculus fibularis longus (peroneus longus)',
 'petittubercle': 'tuberculum minus humeri',
 'petrosal sinus': 'sinus petrosus',
 'petrous segment of internal carotid artery': 'pars petrosa arteriae carotidis internae',
 'piriformis2': 'musculus piriformis',
 'pituitary infundibulum': 'infundibulum hypophysis',
 'popliteal groove': 'sulcus popliteus (sulcus musculi poplitei femoris)',
 'popliteal tendon': 'tendo musculi poplitei',
 'poplitealartery': 'arteria poplitea',
 'poplitealgroove': 'sulcus popliteus',
 'post lateral meniscus': 'cornu posterius menisci lateralis',
 'posterior clinoid process': 'processus clinoideus posterior',
 'posterior crus of right internal capsule': 'crus posterius capsulae internae dextrae',
 'posterior horn of medial meniscus': 'cornu posterius menisci medialis',
 'posterior lobe of pituitary': 'lobus posterior hypophysis (neurohypophysis)',
 'posterior myometrium': 'myometrium posterius',
 'posterior wall of urinary bladder': 'paries posterior vesicae urinariae',
 'pouch of douglas': 'excavatio rectouterina (Douglasi)',
 'pre pontine cistern': 'cisterna prepontina',
 'prevertebral soft tissue': 'textus mollis prevertebralis (spatium prevertebrale)',
 'processstyloidradii': 'processus styloideus radii',
 'proculna': 'extremitas proximalis ulnae (ulna proximalis)',
 'profunda femoris artery': 'arteria profunda femoris',
 'prostate central': 'zona centralis prostatae',
 'prostate gland': 'prostata (glandula prostatica)',
 'prostatic capsule': 'capsula prostatae',
 'prostatic portion of urethra': 'pars prostatica urethrae',
 'proxfemur': 'extremitas proximalis femoris (femur proximale)',
 'proximal radius': 'extremitas proximalis radii (radius proximalis)',
 'proximal tibia': 'extremitas proximalis tibiae (tibia proximalis)',
 'proximal ulna': 'extremitas proximalis ulnae (ulna proximalis)',
 'pudendal artery': 'arteria pudenda interna',
 'quadrigeminal plate': 'lamina quadrigemina (lamina tecti)',
 'radial head': 'caput radii',
 'radial neck': 'collum radii',
 'renal cortex of lower pole of right kidney': 'cortex renalis poli inferioris renis dextri',
 'renal cortex of upper pole of left kidney': 'cortex renalis poli superioris renis sinistri',
 'renal pelvis of right kidney': 'pelvis renalis dextra',
 'renal sinus fat': 'corpus adiposum sinus renalis',
 'retroglandular fat': 'textus adiposus retroglandularis mammae',
 'right ampulla of fallopian tube': 'ampulla tubae uterinae dextrae',
 'right carotid foramen': 'foramen caroticum dextrum',
 'right central sulcus of rolando': 'sulcus centralis (Rolandi) dexter',
 'right cerebellopontine angle cistern': 'cisterna anguli cerebellopontini dextra',
 'right cortical vein': 'vena corticalis dextra',
 'right distal ureter': 'pars distalis ureteris dextri',
 'right fibroglandular breast tissue': 'textus fibroglandularis mammae dextrae',
 'right fimbria of fallopian tube': 'fimbriae tubae uterinae dextrae',
 'right greater horn of hyoid bone': 'cornu majus ossis hyoidei dextrum',
 'right head of malleus': 'caput mallei dextri',
 'right hemidiaphragm': 'hemidiaphragma dextrum',
 'right inferior pole renal calyx': 'calyx renalis poli inferioris dexter',
 'right inferior second molar tooth': 'dens molaris secundus inferior dexter',
 'right internal acoustic meatus': 'meatus acusticus internus dexter',
 'right interstitial portion of fallopian tube': 'pars uterina (intramuralis) tubae uterinae dextrae',
 'right intraperitoneal spillage of contrast': 'cavitas peritonealis dextra',
 'right isthmus of fallopian tube': 'isthmus tubae uterinae dextrae',
 'right kidney inferior pole': 'polus inferior renis dextri (extremitas inferior)',
 'right kidney upper pole major calyx': 'calyx renalis major poli superioris renis dextri',
 'right lateral pterygoid process of sphenoid': 'lamina lateralis processus pterygoidei ossis sphenoidalis dextra',
 'right lobe of thyroid gland': 'lobus dexter glandulae thyroideae',
 'right masticator space': 'spatium masticatorium dextrum',
 'right maxillary sinus infundibulum': 'infundibulum sinus maxillaris dextrum',
 'right peripheral zone of prostate gland': 'zona peripherica prostatae dextra',
 'right petrous segment of internal carotid artery': 'pars petrosa arteriae carotidis internae dextrae',
 'right post central gyrus': 'gyrus postcentralis dexter',
 'right proximal ureter': 'pars proximalis ureteris dextri',
 'right ramus of hemimandible': 'ramus mandibulae dexter',
 'right suprarenal gland': 'glandula suprarenalis dextra',
 'right temporal bone styloid process': 'processus styloideus ossis temporalis dexter',
 'right ureterovesical junction': 'junctio ureterovesicalis dextra',
 'right vallecula': 'vallecula epiglottica dextra',
 'right vertebral artery (2)': 'arteria vertebralis dextra',
 'right vesicular glands': 'glandulae vesiculosae dextrae (vesicula seminalis)',
 'rightcomfem': 'vena femoralis communis dextra',
 's1 foramen': 'foramen sacrale S1',
 'sacral ala': 'ala ossis sacri',
 'sacral foramen': 'foramen sacrale',
 'sacralala': 'ala ossis sacri',
 'sacralfor': 'foramen sacrale',
 'saphenous vein': 'vena saphena',
 'sartorius': 'musculus sartorius',
 'sartorius1': 'musculus sartorius',
 'scaph1': 'os scaphoideum',
 'segmental vessel of kidney': 'arteria segmentalis renis (vasa segmentalia renis)',
 'semimembranosus2': 'musculus semimembranosus',
 'short head of biceps': 'caput breve musculi bicipitis brachii',
 'sphenoid air sinus': 'sinus sphenoidalis',
 'spinascapulae2': 'spina scapulae',
 'spinousprocessc7': 'processus spinosus vertebrae C7',
 'splenium of corpus callosum': 'splenium corporis callosi',
 "stensen's duct": 'ductus parotideus (Stenonis)',
 'sthmus of right fallopian tube': 'isthmus tubae uterinae dextrae',
 'styloid process': 'processus styloideus',
 'suparticprocess': 'processus articularis superior',
 'superficialarteryfem': 'arteria femoralis superficialis',
 'superior articular process': 'processus articularis superior',
 'superior longitudinal sinus': 'sinus sagittalis superior',
 'superior minor calyx of the upper pole of the right kidney': 'calyx renalis minor poli superioris renis dextri',
 'superior orbital fissures': 'fissura orbitalis superior',
 'suppubramus': 'ramus superior ossis pubis',
 'supraclinoid segment of internal carotid artery': 'pars supraclinoidea (pars cerebralis) arteriae carotidis internae',
 'suprapate': 'recessus suprapatellaris',
 'suprapatellar fat pad': 'corpus adiposum suprapatellare',
 'suprapatellarfatpad': 'corpus adiposum suprapatellare',
 'suprasellar cistern': 'cisterna suprasellaris (cisterna chiasmatica)',
 'suspensory ligament of cooper': 'ligamenta suspensoria mammae (Cooper)',
 'sylvian fissure': 'sulcus lateralis cerebri (fissura Sylvii)',
 'symphysis of mandible': 'symphysis mandibulae (symphysis menti)',
 'tail of epididymis': 'cauda epididymidis',
 'talar body': 'corpus tali',
 'talar head': 'caput tali',
 'talar neck': 'collum tali',
 'talus ossification center': 'centrum ossificationis tali',
 'temporal horn of lateral ventricle': 'cornu temporale ventriculi lateralis',
 'tensor fascia latae': 'musculus tensor fasciae latae',
 'tentorial sinus': 'sinus tentorii',
 'teresmajor': 'musculus teres major',
 'testicular mediastinum': 'mediastinum testis',
 'testicular sac': 'scrotum (saccus testis)',
 'testicule': 'testis',
 'tfcc': 'complexus fibrocartilagineus triangularis (discus articularis)',
 'thoracic oesophagus': 'pars thoracica oesophagi',
 'thoracicintervertebralforamen': 'foramen intervertebrale thoracicum',
 'tibial tuberosity': 'tuberositas tibiae',
 'tibial vein': 'vena tibialis',
 'tibiofibular syndesmosis': 'syndesmosis tibiofibularis',
 'tibiofibular trunk': 'truncus tibiofibularis',
 'tibiofibularistrunk': 'truncus tibiofibularis',
 'tonsils of cerebellum': 'tonsilla cerebelli',
 'transitional zone of prostate': 'zona transitionalis prostatae',
 'transproce': 'processus transversus',
 'transverse': 'processus transversus',
 'transverse sinus': 'sinus transversus',
 'transversec1': 'processus transversus atlantis (C1)',
 'transversepr': 'processus transversus',
 'transverseprocess': 'processus transversus',
 'transverseprocess é': 'processus transversus',
 'transversus abdominis': 'musculus transversus abdominis',
 'trapezium1': 'os trapezium',
 'trapezium3': 'os trapezium',
 'trapezium4': 'os trapezium',
 'trapezium5': 'os trapezium',
 'trapezius5': 'musculus trapezius',
 'trapezius6': 'musculus trapezius',
 'tuberositetibia': 'tuberositas tibiae',
 'tunica albuginea': 'tunica albuginea testis',
 'tunique vaginale': 'tunica vaginalis testis',
 'ulnar shaft': 'corpus ulnae (diaphysis ulnae)',
 'ulnar styloid': 'processus styloideus ulnae',
 'upper pole of kidney': 'extremitas superior renis (polus superior)',
 'urinary bladder dome': 'apex vesicae urinariae (vertex vesicae)',
 'urinary bladder neck': 'cervix vesicae urinariae (collum vesicae)',
 'urinary bladder trigone': 'trigonum vesicae urinariae',
 'urothelium': 'urothelium (tunica mucosa vesicae)',
 'vaginal canal': 'canalis vaginae (vagina)',
 'vallecula': 'vallecula epiglottica',
 'vastus lateralis': 'musculus vastus lateralis',
 'vermis of cerebellum': 'vermis cerebelli',
 'vertebral body c2': 'corpus vertebrae C2 (axis)',
 'vocal cord': 'plica vocalis',
 'xraymusculoskeletal197': '— (bestandsnaam, geen anatomische term)',
 'xraymusculoskeletal222': '— (bestandsnaam, geen anatomische term)',
 'xraymusculoskeletal91': '— (bestandsnaam, geen anatomische term)',
 'zygapophyseal joint': 'articulatio zygapophysialis',
 'zygoap': 'articulatio zygapophysialis',
 'zygoapophyseal': 'articulatio zygapophysialis',
 'zygoapophysealjoint': 'articulatio zygapophysialis',
 'zygomaticofrontalsuture': 'sutura frontozygomatica'}
